### ISSUE TITLE
Can't walk dependency graph

### ISSUE THREAD

**Issue by octava25** [ajaxorg/ace#4753]
Hello, after upgrading react-ace from 3.4.1 to latest(9.3.0) i see a lot of errors with "Can't walk dependency graph".

Some examples:
`Error: Can't walk dependency graph: Cannot find module '../split' from '/opt/repo/web/node_modules/ace-builds/src-noconflict/ext-split.js'
required by /opt/repo/web/node_modules/ace-builds/src-noconflict/ext-split.js`

`Error: Can't walk dependency graph: Cannot find module './editor' from '/opt/repo/web/node_modules/ace-builds/src-noconflict/ext-split.js'
required by /opt/repo/web/node_modules/ace-builds/src-noconflict/ext-split.js`

`Error: Can't walk dependency graph: Cannot find module './mode/folding/fold_mode' from '/opt/repo/web/node_modules/ace-builds/src-noconflict/ace.js' required by /opt/repo/web/node_modules/ace-builds/src-noconflict/ace.js`

package.js:
```
{
   ....
  "dependencies": {
    ....
    "ace-builds": "1.4.12",
    "react-ace": "^9.3.0",
    ....
  },
 "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "@babel/preset-react",
            "@babel/preset-env"
          ]
        }
      ],
      "envify"
    ]
  }
}
```

I followed migrations steps from here: https://github.com/securingsincity/react-ace/blob/master/docs/Migrate-v7-to-v8.md

**Comment by andrewnester** [comment]
Please reach out to react-ace as it seems to be the issue on their side
